version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_DB=inventory-db
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
    ports:
      - '5432:5432'
    networks:
      - app

networks:
  app:
    driver: bridge